# Generated by Django 4.0.8 on 2023-11-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_date_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy_policy_agreement',
            field=models.BooleanField(default=False),
        ),
    ]
