# Generated by Django 4.0.8 on 2023-11-10 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Выберите жанр', related_name='books', to='catalog.genre'),
        ),
    ]
