# Generated by Django 4.0.8 on 2023-11-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(error_messages={'unique': 'Жанр с таким именем уже существует.'}, help_text='Введите жанр книги (например, научная фантастика, французская поэзия и т. д.)', max_length=200, unique=True),
        ),
    ]
