# Generated by Django 4.0.8 on 2023-11-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_genre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(error_messages={'unique': 'Такой язык уже существует.'}, help_text='Введите естественный язык книги (например, английский, французский, японский и т. д.)', max_length=200, unique=True),
        ),
    ]
