# Generated by Django 4.0.8 on 2023-11-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_language_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(error_messages={'unique': 'Жанр с таким именем уже существует.'}, help_text='Введите жанр книги (например, научная фантастика, французская поэзия и т. д.)', max_length=200, unique=True, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(error_messages={'unique': 'Такой язык уже существует.'}, help_text='Введите естественный язык книги (например, английский, французский, японский и т. д.)', max_length=200, unique=True, verbose_name='Язык'),
        ),
    ]
