# Generated by Django 4.0.8 on 2023-11-11 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_edition_publication_date_remove_edition_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(help_text='Название', max_length=200)),
                ('adress', models.CharField(help_text='Издательство', max_length=200)),
                ('telephone_number', models.CharField(help_text='Номер телефона', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='bookcopy',
            name='due_back',
        ),
        migrations.RemoveField(
            model_name='bookcopy',
            name='edition',
        ),
        migrations.DeleteModel(
            name='Edition',
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.publisher'),
        ),
    ]
