# Generated by Django 4.0.8 on 2023-11-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_publisher_remove_bookcopy_due_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='adress',
            field=models.CharField(help_text='Адрес издательства', max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher',
            field=models.CharField(help_text='Название издательства', max_length=200, verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='telephone_number',
            field=models.CharField(help_text='Номер телефона издательства', max_length=200, verbose_name='Номер телефона'),
        ),
    ]
