# Generated by Django 4.0.8 on 2023-11-11 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_publisher_adress_alter_publisher_publisher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='adress',
            field=models.CharField(max_length=200, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='publisher',
            field=models.CharField(max_length=200, verbose_name='Издательство'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='telephone_number',
            field=models.CharField(max_length=200, verbose_name='Номер телефона'),
        ),
    ]
