# Generated by Django 4.0.8 on 2023-11-16 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_publisher_adress_alter_publisher_publisher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='author',
            field=models.ForeignKey(blank=True, default=11, on_delete=django.db.models.deletion.RESTRICT, to='catalog.author'),
            preserve_default=False,
        ),
    ]
