# Generated by Django 4.0.8 on 2023-11-16 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0012_bookinstance_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcopy',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='bookinstance',
            name='author',
        ),
        migrations.AddField(
            model_name='bookinstance',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worked_books', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
