# Generated by Django 4.0.8 on 2023-11-16 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_remove_bookcopy_publisher_remove_bookinstance_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name', 'middle_name']},
        ),
    ]
