# Generated by Django 4.0.8 on 2024-01-04 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_remove_positionacceptact_acceptact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.RemoveField(
            model_name='positionacceptact',
            name='copy',
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='positionAcceptAct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.positionacceptact', verbose_name='Позиция акта послупления'),
        ),
        migrations.CreateModel(
            name='BookExemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_manufacture', models.DateField(blank=True, null=True, verbose_name='Дата изготовления')),
                ('city_of_publication', models.CharField(max_length=100, verbose_name='Город издания')),
                ('publication_type', models.CharField(blank=True, choices=[('к', 'Книги'), ('ж', 'Журналы'), ('г', 'Газеты'), ('э', 'Электронные ресурсы'), ('м', 'Мультимедийные материалы'), ('р', 'Реферативные издания'), ('у', 'Учебники и учебные пособия')], default='р', max_length=1, verbose_name='Тип издания')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.book', verbose_name='Книга')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='catalog.publisher', verbose_name='Издательство')),
            ],
        ),
        migrations.AddField(
            model_name='positionacceptact',
            name='exemplar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.bookexemplar', verbose_name='Экземпляр'),
        ),
    ]
