# Generated by Django 5.0.1 on 2024-01-06 09:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_publisher_remove_positionacceptact_copy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookexemplar',
            name='publication_type',
            field=models.CharField(blank=True, choices=[('к', 'Книги'), ('ж', 'Журналы'), ('г', 'Газеты'), ('э', 'Электронные ресурсы'), ('м', 'Мультимедийные материалы'), ('р', 'Реферативные издания'), ('у', 'Учебники и учебные пособия')], default='к', max_length=1, verbose_name='Тип издания'),
        ),
        migrations.CreateModel(
            name='AccountingBookCopy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор', primary_key=True, serialize=False)),
                ('date_of_creation', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='accountingBookCopy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalog.accountingbookcopy', verbose_name='Позиция учёта экземпляра'),
        ),
    ]

