# Generated by Django 5.0.1 on 2024-01-06 09:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_bookexemplar_publication_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebitingAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.DateField(default=django.utils.timezone.now, verbose_name='Текущая дата')),
                ('Tip', models.CharField(blank=True, choices=[('а', 'Амортизация'), ('у', 'Устаревание'), ('п', 'Повреждение'), ('у', 'Утрата')], default='п', max_length=1, verbose_name='Тип списания')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='PositionDebitingAct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=100, verbose_name='Цена')),
                ('debiting_act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_debiting_acts', to='catalog.debitingact', verbose_name='Акт о приёме')),
                ('debiting_exemplar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.bookcopy', verbose_name='Учтённый экземпляр')),
            ],
        ),
    ]
