# Generated by Django 5.0.1 on 2024-01-09 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_debitingact_positiondebitingact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.CharField(blank=True, choices=[('р', 'Выдано'), ('д', 'Доступно'), ('з', 'Зарезервировано'), ('с', 'Списано')], default='д', help_text='Доступность книги', max_length=1, verbose_name='Статус'),
        ),
    ]
