# Generated by Django 5.0.1 on 2024-01-09 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_bookcopy_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitingact',
            name='Tip',
            field=models.CharField(blank=True, choices=[('а', 'Амортизация'), ('с', 'Устаревание'), ('п', 'Повреждение'), ('у', 'Утрата')], default='п', max_length=1, verbose_name='Тип списания'),
        ),
    ]
