# Generated by Django 5.0.1 on 2024-01-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_debitingact_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptact',
            name='number',
            field=models.CharField(default=1, max_length=100, verbose_name='Номер акта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debitingact',
            name='number',
            field=models.CharField(default=1, max_length=100, verbose_name='Номер акта'),
            preserve_default=False,
        ),
    ]
