# Generated by Django 5.0.1 on 2024-01-10 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_acceptact_number_debitingact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debitingact',
            name='Tip',
        ),
    ]
