# Generated by Django 5.0.1 on 2024-01-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_positiondebitingact_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='fizpersonsource',
            name='contact_information',
            field=models.CharField(max_length=100, null=True, verbose_name='Контактные данные'),
        ),
        migrations.AddField(
            model_name='source',
            name='address',
            field=models.CharField(default=1, max_length=100, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
    ]
