# Generated by Django 5.0.1 on 2024-03-25 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_fizpersonsource_contact_information_source_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Тип')),
                ('number', models.CharField(max_length=100, verbose_name='Номер')),
                ('number_seats', models.CharField(max_length=100, verbose_name='Количество мест')),
            ],
        ),
        migrations.CreateModel(
            name='TypeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=100, null=True, verbose_name='Отчество')),
                ('event_name', models.CharField(max_length=100, verbose_name='Наименование мероприятия')),
                ('number_of_participants', models.CharField(max_length=100, verbose_name='Цена')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата начала проведения')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата конца проведения')),
                ('date_end2', models.DateField(blank=True, null=True, verbose_name='Дата фактического окончания')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.room')),
                ('typeevent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.typeevent')),
            ],
        ),
        migrations.CreateModel(
            name='PositionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('date_record', models.DateField(blank=True, null=True, verbose_name='Дата начала проведения')),
                ('status_record', models.CharField(blank=True, choices=[('з', 'записан'), ('н', 'не записан')], default='н', max_length=1, verbose_name='Статус записи')),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Абонент')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.event')),
            ],
        ),
    ]
