# Generated by Django 5.0.1 on 2024-03-26 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_room_typeroom_event_positionevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='typeevent',
        ),
        migrations.AlterField(
            model_name='event',
            name='number_of_participants',
            field=models.CharField(max_length=100, verbose_name='Количество участников'),
        ),
        migrations.AddField(
            model_name='event',
            name='typeroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.typeroom'),
        ),
        migrations.DeleteModel(
            name='TypeEvent',
        ),
    ]
