# Generated by Django 5.0.1 on 2024-03-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0027_typeroom_remove_event_typeevent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='middle_name',
        ),
    ]
