# Generated by Django 5.0.1 on 2024-03-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0028_remove_event_first_name_remove_event_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.CharField(default=1, max_length=100, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='fio',
            field=models.CharField(default=1, max_length=100, verbose_name='ФИО организатора'),
            preserve_default=False,
        ),
    ]
