# Generated by Django 5.0.1 on 2024-03-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_event_description_event_fio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeroom',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Наименование'),
        ),
    ]
