# Generated by Django 5.0.1 on 2024-03-26 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_alter_typeroom_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionevent',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='positionevent',
            name='date_record',
            field=models.DateField(blank=True, null=True, verbose_name='Дата регистрации'),
        ),
    ]
