# Generated by Django 5.0.1 on 2024-04-05 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_remove_positionevent_last_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionevent',
            name='status_record',
            field=models.CharField(blank=True, choices=[('з', 'записан'), ('н', 'не записан')], default='з', max_length=1, verbose_name='Статус записи'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=100, verbose_name='Описание')),
                ('date_creation', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('status_record', models.CharField(blank=True, choices=[('п', 'принята'), ('з', 'закрыта'), ('в', 'в обработке'), ('о', 'отклонено')], default='в', max_length=1, verbose_name='Статус заявки-')),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Абонент')),
                ('worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worked_request', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'ordering': ['title', 'author'],
            },
        ),
    ]
