# Generated by Django 5.0.1 on 2024-04-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_alter_positionevent_status_record_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Описание'),
        ),
    ]
