# Generated by Django 5.0.1 on 2024-04-12 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positionevent',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.event'),
        ),
    ]
