# Generated by Django 5.0.1 on 2024-05-04 14:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_alter_bookinstance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='current_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='due_back',
            field=models.DateField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='renewal_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата продления'),
        ),
        migrations.AlterField(
            model_name='positionevent',
            name='status_record',
            field=models.CharField(blank=True, choices=[('з', 'записан'), ('н', 'не записан'), ('о', 'окончено')], default='з', max_length=1, verbose_name='Статус записи'),
        ),
    ]
