# Generated by Django 5.0.1 on 2024-05-07 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0038_alter_bookinstance_due_back_history_of_appeals'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_of_appeals',
            name='bookinstance',
        ),
        migrations.AddField(
            model_name='history_of_appeals',
            name='bookinstance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.bookinstance'),
        ),
    ]
