# Generated by Django 5.0.1 on 2024-05-08 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0039_remove_history_of_appeals_bookinstance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_of_appeals',
            name='date_creation',
            field=models.DateField(blank=True, null=True, verbose_name='Дата создания'),
        ),
    ]
