# Generated by Django 5.0.1 on 2024-05-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_alter_event_date_end_alter_event_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='acceptact',
            name='status_record',
            field=models.CharField(blank=True, choices=[('у', 'учтено'), ('н', 'не учтено')], default='з', max_length=1, verbose_name='Статус записи'),
        ),
    ]
