# Generated by Django 5.0.1 on 2024-05-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0043_acceptact_status_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionacceptact',
            name='status_record',
            field=models.CharField(blank=True, choices=[('у', 'учтено'), ('н', 'не учтено')], default='н', max_length=1, verbose_name='Статус записи'),
        ),
        migrations.AlterField(
            model_name='acceptact',
            name='status_record',
            field=models.CharField(blank=True, choices=[('у', 'учтено'), ('н', 'не учтено')], default='н', max_length=1, verbose_name='Статус записи'),
        ),
    ]
