# Generated by Django 5.0.1 on 2024-05-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0044_positionacceptact_status_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата возврата'),
        ),
    ]
