# Generated by Django 5.0.1 on 2024-05-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_news_date_creation_news_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='title_image',
            field=models.ImageField(blank=True, null=True, upload_to='news_title_images/', verbose_name='Титульное изображение'),
        ),
    ]
