# Generated by Django 5.0.1 on 2024-05-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_news_title_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookexemplar',
            name='bbk',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ББК'),
        ),
        migrations.AddField(
            model_name='bookexemplar',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ISBN'),
        ),
        migrations.AddField(
            model_name='bookexemplar',
            name='udc',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='УДК'),
        ),
    ]
