# Generated by Django 5.0.1 on 2024-05-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0049_bookexemplar_bbk_bookexemplar_isbn_bookexemplar_udc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookexemplar',
            name='bbk',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ББК'),
        ),
        migrations.AlterField(
            model_name='bookexemplar',
            name='isbn',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='bookexemplar',
            name='publication_type',
            field=models.CharField(blank=True, choices=[('к', 'Книга'), ('ж', 'Журнал'), ('г', 'Газета'), ('э', 'Электронный ресурс'), ('м', 'Мультимедийный материал'), ('р', 'Реферативное издание'), ('у', 'Учебники и учебные пособия')], default='к', max_length=1, verbose_name='Тип издания'),
        ),
        migrations.AlterField(
            model_name='bookexemplar',
            name='udc',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='УДК'),
        ),
    ]
